// <auto-generated />
using System;
using DevTrack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevTrack.Infrastructure.Migrations
{
    [DbContext(typeof(DevTrackDbContext))]
    partial class DevTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevTrack.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatusNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("RepoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TechStack")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Type");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.ComponentTag", b =>
                {
                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ComponentTags", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alternatives")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LearningModuleId")
                        .HasColumnType("integer");

                    b.Property<int?>("LearningTrackId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("DecidedAt");

                    b.HasIndex("LearningModuleId");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Decisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Decisions_Owner_ExactlyOne", "(CASE WHEN \"ProjectId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"ComponentId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningTrackId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningModuleId\" IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ConvertedNextStepId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConvertedToNextStep")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LearningModuleId")
                        .HasColumnType("integer");

                    b.Property<int?>("LearningTrackId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ConvertedNextStepId");

                    b.HasIndex("IsConvertedToNextStep");

                    b.HasIndex("LearningModuleId");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ideas_Owner_ExactlyOne", "(CASE WHEN \"ProjectId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"ComponentId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningTrackId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningModuleId\" IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.LearningModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LearningTrackId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("LearningTrackId", "Order");

                    b.ToTable("LearningModules", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.LearningTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("LearningTracks", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.LearningTrackTag", b =>
                {
                    b.Property<int>("LearningTrackId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("LearningTrackId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LearningTrackTags", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.NextStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LearningModuleId")
                        .HasColumnType("integer");

                    b.Property<int?>("LearningTrackId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("LearningModuleId");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("Priority");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("NextSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_NextSteps_Owner_ExactlyOne", "(CASE WHEN \"ProjectId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"ComponentId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningTrackId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningModuleId\" IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Goal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.ProjectTag", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTags", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("RelatedLearningTrackId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("IsDismissed");

                    b.HasIndex("IsRead");

                    b.HasIndex("RelatedLearningTrackId");

                    b.HasIndex("RelatedProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LearningModuleId")
                        .HasColumnType("integer");

                    b.Property<int?>("LearningTrackId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("LearningModuleId");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Resources", null, t =>
                        {
                            t.HasCheckConstraint("CK_Resources_Owner_ExactlyOne", "(CASE WHEN \"ProjectId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"ComponentId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningTrackId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningModuleId\" IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Worklog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LearningModuleId")
                        .HasColumnType("integer");

                    b.Property<int?>("LearningTrackId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WhatIDid")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("WhatsLeft")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("LearningModuleId");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("LoggedAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Worklogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Worklogs_Owner_ExactlyOne", "(CASE WHEN \"ProjectId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"ComponentId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningTrackId\" IS NULL THEN 0 ELSE 1 END + CASE WHEN \"LearningModuleId\" IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Component", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Project", "Project")
                        .WithMany("Components")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.ComponentTag", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Component", "Component")
                        .WithMany("ComponentTags")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevTrack.Domain.Entities.Tag", "Tag")
                        .WithMany("ComponentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Decision", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningModule", "LearningModule")
                        .WithMany()
                        .HasForeignKey("LearningModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("LearningModule");

                    b.Navigation("LearningTrack");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Idea", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.NextStep", "ConvertedNextStep")
                        .WithMany()
                        .HasForeignKey("ConvertedNextStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningModule", "LearningModule")
                        .WithMany()
                        .HasForeignKey("LearningModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("ConvertedNextStep");

                    b.Navigation("LearningModule");

                    b.Navigation("LearningTrack");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.LearningModule", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany("Modules")
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningTrack");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.LearningTrack", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany("LearningTracks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.LearningTrackTag", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany("LearningTrackTags")
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevTrack.Domain.Entities.Tag", "Tag")
                        .WithMany("LearningTrackTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningTrack");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.NextStep", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningModule", "LearningModule")
                        .WithMany()
                        .HasForeignKey("LearningModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("LearningModule");

                    b.Navigation("LearningTrack");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Project", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.ProjectTag", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevTrack.Domain.Entities.Tag", "Tag")
                        .WithMany("ProjectTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "RelatedLearningTrack")
                        .WithMany()
                        .HasForeignKey("RelatedLearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.Project", "RelatedProject")
                        .WithMany()
                        .HasForeignKey("RelatedProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedLearningTrack");

                    b.Navigation("RelatedProject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Resource", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningModule", "LearningModule")
                        .WithMany()
                        .HasForeignKey("LearningModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("LearningModule");

                    b.Navigation("LearningTrack");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Tag", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Worklog", b =>
                {
                    b.HasOne("DevTrack.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningModule", "LearningModule")
                        .WithMany()
                        .HasForeignKey("LearningModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany()
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("LearningModule");

                    b.Navigation("LearningTrack");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Component", b =>
                {
                    b.Navigation("ComponentTags");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.LearningTrack", b =>
                {
                    b.Navigation("LearningTrackTags");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Project", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("ProjectTags");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ComponentTags");

                    b.Navigation("LearningTrackTags");

                    b.Navigation("ProjectTags");
                });

            modelBuilder.Entity("DevTrack.Domain.Entities.User", b =>
                {
                    b.Navigation("LearningTracks");

                    b.Navigation("Projects");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
